<?php

namespace AppBundle\Repository;

/**
 * WordCountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordCountRepository extends \Doctrine\ORM\EntityRepository
{
}
